[pytest]
filterwarnings =
    ignore:Type google\._upb\._message\.MessageMapContainer uses PyType_Spec.*:DeprecationWarning
    ignore:Type google\._upb\._message\.ScalarMapContainer uses PyType_Spec.*:DeprecationWarning
